### PR TITLE
Redwood tree worldgen

### PR DESCRIPTION
**Pull request by BrewingCoder**
Redwood Tree World Gen, upped to 1.10.

### CODE REVIEW

**Comment by Drullkus** [comment]
What the hell is this code? Did you just copy paste this?

**Comment by BrewingCoder** [comment]
It's the 1.7.10 code upped to work with 1.10.  why the hell is that a problem?

**Comment by BrewingCoder** [comment]
The way I saw it the current branches don't have a redwood tree gen; yes the old code was messy.  Lots of stuff could be changed/optimized.  But this  brings it functionally up to 1.10 without weeks of re-write.  Natura is missing one of it's biggest features, the Redwood.  Now it gen's exactly like 1.7.10; but  working in 1.10.  Yes; I could have spent two weeks changing every coord call to BlockPos, could have changed all those long stupid lists of calls to change states to iterators; but it works. and it build, and it generates perfectly.  If you don't like it don't accept the pull and sorry for trying to help out.

**Comment by Drullkus** [comment]
You could have just spent less time rewriting this dump, TBH.

**Comment by BrewingCoder** [comment]
Less time?  I mean all told this was a few hours work over the weekend.  And to be honest My desire was not to re-write but to respect the original code; and the original tree.  
The redwood tree is classic -- and it's not like the code breaks anything.

I have no problem taking ownership of it and cleaning it up; but it deserves a chance to get back in the pack instead of being ignored.  Maybe at least this pull request will get it attention then.

**Comment by Drullkus** [comment]
I'll clarify. There's some really easy spots to optimize. There's sections of the code where it's plain stupid repetition that can be really easily fixed with a for loop with no additional effort. Then there's some more optimizations that can be made with very little effort related to other repetition.

This could have saved you time instead of replacing so much code.

Also you can select all with a find function and replace all.

**Comment by BrewAndCode** [comment]
I'm a lazy programmer.. I do search/replace really well. which is how this got to where it was.  

But I also know code-owners; and they tend not to like total rewrites of their shit -- so this was the result.

**Comment by BrewingCoder** [comment]
btw; If you think I typed all those damn calls to setBlockAndNotify... you're mistaken -- IntelliJ Refactor and search/replace did it all; hence why I did it while watching ball games on Sunday.

Seriously though? I mean the last commits to this repo were 30 days ago and they were crash/fix -- I push a request that adds back in missing functionality doing minimal work from the old code base and I get shit?

**Comment by Drullkus** [comment]
I'm flattered that you think I work on Natura... I actually don't. 😉

**Comment by alexbegt** [comment]
I have gone and wrote the world generator myself, so that It would be more updated code as the 1.7.10 code is from like minecraft 1.2.5 and I feel it would be a bad idea having that on 1.10.2.

**Pull request closed without merging**
