### PR TITLE
Fixes Bookshelfs dropping books without texture

### PR DESCRIPTION
**Pull request by BloodWorkXGaming**
Otherwise the books look like that:
image

This fix might be needed on the 1.11 branch as well

### CODE REVIEW

**Comment by alexbegt** [comment]
Git says I edited your pull request? o-o

**Comment by BloodWorkXGaming** [comment]
your jenkins automatically made this build here https://dvs1.progwml6.com/jenkins/job/natura-prtests/73/
no idea why it is 1.7.10 on a 1.10 branch

**Comment by BloodWorkXGaming** [comment]
As a beginning mod dev I do have a question: is there any reason why you chose your way over mine?
Just a thing of preference or has it any benefits?

**Comment by alexbegt** [comment]
Your way was fine, but I did it my way to keep it in the standard on how Natura 1.7.10 did it, I am sorry if it seemed I chose my way over yours. It also seems I broke pickblocking while in creative with my way lol.

**Pull request closed without merging**
