### PR TITLE
Fixed ghostwood not generating

### PR DESCRIPTION
**Pull request by Sinhika**
You probably should ignore the changes to .gitignore, build.properties, & build.gradle, since those were just to get it to build on my system. The important change is in WhiteTreeGen.java.

### CODE REVIEW

**Comment by alexbegt** [comment]
If you want us to ignore then, Why didn't you just push it with only the code change, Github client allows you to select what you want to push.

**Comment by bonii-xx** [comment]
http://jaxenter.com/10-commandments-committing-pull-requests-115707.html

**Comment by Sinhika** [comment]
Is there a way to prune what goes into a pull request once it's been pushed to your own fork on github? I was tired and forgot to only push the specific files I wanted up to GitHub, then realized the mistake when I was trying to assemble the pull request. I couldn't find anything in the GitHub interface...

**Comment by TherminatorX** [comment]
@Sinhika Just close this one and open a new.

**Comment by Sinhika** [comment]
Will do that, then

**Pull request closed without merging**
