### PR TITLE
Fix #182. Fix #183. Refactoring of saplings code.

### LINKED ISSUE #182: NSaplingItem wont grow on Forestry Soil (humus)
Hello,

I'm work on bugfixes in Forestry and noticed that NSaplings will not grow on humus, which is the soil used for Forestry's multifarms. It all comes down to `NSaplingBlock canThisPlantGrowOnThisBlock`, which is quite strict. 

``` java
   public boolean canThisPlantGrowOnThisBlock (Block id)
    {
        return id == Blocks.grass || id == Blocks.dirt || id == Blocks.soul_sand || id == Blocks.netherrack || id == NContent.taintedSoil;
    }
```

The OverworldSaplings grow just fine, so hopefully there is a simple solution.
I don't think we should be able to grow the bloodwood saplings on humus, but some of the others would be nice.

Steps to reproduce:
1. Put down a block of humus.
2. Try to place a Sakura Sapling on it.

Thank you! :bee:

Checked on Forestry 3.0.0.125 and natura-1.7.10-2.2.0-b1

### LINKED ISSUE #183: OverworldSaplings can be placed everywhere
OverworldSaplings bypass the regular sapling checks and can be placed anywhere a regular block can be placed.
They will eventually pop off when `canBlockStay` gets called.

Checked with natura-1.7.10-2.2.0-b1, forge 1207

### PR DESCRIPTION
**Pull request by mezz**
Now there are 3 categories: Flora Sapling, Rare Sapling, and Nether Sapling.

I worked hard to clarify the sapling code and get rid of some more subtle bugs. 
I tested by planting each type of sapling on various soils, letting them grow naturally, and using bonemeal on them.
Checked that: 
- Sapling names stay the same
- textures are correct
- tooltip is correct
- tree it grows into is correct
- can't be placed on the wrong soil
- can be placed on soil that supports it
- bonemeal fails if growth conditions are not met (redwood)
- saplings show up correctly in creative inventory and NEI

This will break some saplings in existing worlds, but doesn't touch trees or leaves. Since 1.7.10 is very early and still not in stable packs, I think this is the right time to make this change.

Cheers :bee:

### CODE REVIEW

**Comment by Adaptivity** [comment]
@alexbegt maybe you can take a look at this again? Just don't rename stuff and this shouldn't break anything, right? This should fix dozens of bugs in 1.7... please just take a look.

**Comment by progwml6** [comment]
splitting them WILL break things unfortunately

**Comment by Adaptivity** [comment]
Maybe release a separate release? And warn people that saplings in existing worlds will break, don't update if you won't they break? A lot of mods doing releases with breaking changes, you just shouldn't do this frequently. Natura hasn't "stable" release since Oct 8, 2014. No one will blame if you fix tons of bugs but break some saplings...

**Comment by progwml6** [comment]
the issue is that this isn't code breaking its world breaking and i am NOT getting into that support nightmare.

not to mention merging something like this would delay a stable release weeks.

**Comment by Adaptivity** [comment]
Still thinking about it: Mantle remapper will not help us here? Is it still working? Or maybe it's possible to just remove saplings from existing worlds? I think it's a sane solution since saplings are really common and not hard to get things. This is should be possible I think. So, the plan is something like this:
1) Release stable version
2) Pull this and add code to remove old saplings
3) Release new Alpha and warn that saplings in existing worlds will disappear

**Comment by progwml6** [comment]
i'm aware of the techniques. There are forge level problems to remapping this kind of stuff.

I rather have a small bug in a mod than run the risk of destroying someone's world and having items vanish completely.

**Comment by Adaptivity** [comment]
@progwml6 New plan: What if we just register old saplings as "Legacy" so old worlds will not break? Check how Forestry did this: https://github.com/ForestryMC/ForestryMC/commit/a188bbd43ae89ff6fa959d8b95fb9855b9123bdd

**Comment by mezz** [comment]
I used a tile entity to have the old block replace itself with a new one when it gets loaded. It's very hacky so it took a lot of testing to get right, but it can work.

**Comment by progwml6** [comment]
@mezz if we can't replace them in the world we can easily make an old>new recipe and have the saplings change when they get growth ticks.

**Comment by Adaptivity** [comment]
@progwml6 boni added similar thing to ITT, sometimes tool can catch incorrect data (as I know it was due to update from old version to new) and will be useless until you place it in crafting grid. So, maybe add tooltip to saplings (Like: This sapling has incorrect data. Place it in crafting grid.)

**Comment by progwml6** [comment]
These issues should hopefully be fixed in 1.10.2

Redwood and bloodwood are still WIP's for 1.10.2

**Pull request closed without merging**
